### PR TITLE
About us: Sanjida Kazi

### PR DESCRIPTION
**Pull request by sanjidakazi05**
My section for the about us page.

### CODE REVIEW

**Review by mclausen792 — COMMENTED** [review]
There seems to be changes on this branch that aren't for your "about me". Was that intentional?

**Comment by sanjidakazi05** [comment]
> There seems to be changes on this branch that aren't for your "about me". Was that intentional?

Not sure why there were changes, when I made this branch I only worked inside of the about us files.

**Comment by mclausen792** [comment]
Can you try rebasing `git pull --rebase` and re-pushing and see if it removes those changes from your branch?

**Comment by sanjidakazi05** [comment]
> Can you try rebasing `git pull --rebase` and re-pushing and see if it removes those changes from your branch?

When I did those commands, it just says everything is up to date already

**Pull request merged**
